CREATE DATABASE IF NOT EXISTS hyperlocal_retail;
USE hyperlocal_retail;

CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'customer',
  phone VARCHAR(50),
  address TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  category_name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  description TEXT,
  icon VARCHAR(255),
  image VARCHAR(255),
  display_order INT DEFAULT 0,
  is_active TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stores (
  id INT PRIMARY KEY AUTO_INCREMENT,
  store_name VARCHAR(255) NOT NULL,
  owner_name VARCHAR(255),
  product_name VARCHAR(255) NOT NULL,
  category VARCHAR(255),
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  rating DECIMAL(3,2) DEFAULT 4.0,
  total_reviews INT DEFAULT 0,
  shop_number VARCHAR(100),
  street VARCHAR(255),
  market_area VARCHAR(255),
  city VARCHAR(255),
  state VARCHAR(255),
  pincode VARCHAR(50),
  country VARCHAR(100) DEFAULT 'India',
  full_address TEXT,
  latitude DECIMAL(10,7),
  longitude DECIMAL(10,7),
  phone VARCHAR(100),
  is_open TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  product_name VARCHAR(255) NOT NULL,
  brand VARCHAR(255),
  category_id INT NOT NULL,
  store_id INT NOT NULL,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  quantity INT DEFAULT 0,
  image VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE CASCADE,
  FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE,
  INDEX idx_products_store_id (store_id),
  INDEX idx_products_category_id (category_id),
  INDEX idx_products_name (product_name)
);

CREATE TABLE IF NOT EXISTS search_logs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT,
  keyword VARCHAR(255) NOT NULL,
  city VARCHAR(255),
  state VARCHAR(255),
  latitude DECIMAL(10,7),
  longitude DECIMAL(10,7),
  results_found INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);
